#! /bin/sh
# This program attempts to read a file that consists of output from the the
# triptester program to make an SQL database out of it for use with the
# dtc.solving.SQLSolver.

if test $# -lt 2; then
    echo "usage: $0 [-q] [-c size] triptester_file [triptester_files ...] database_file" >&2
    exit 1
fi

PATH=`dirname $0`:$PATH

exec makesql --regex='#\solution => !\tripcode' $@
