import sqlite3

from . import Solver

__all__ = ['SQLSolver']

class SQLSolver (Solver):
    """
    Solver that uses an SQL database for solutions.

    The SQL database must have a table named 'solutions' in which there are
    two columns named 'tripcode' and 'solution', where 'tripcode' is the
    tripcode generated by 'solution'.
    """
    def __init__ (self, dbname):
        """
        Initializes an instance from a database.
        """
        self.dbname = dbname

    def solve (self, tripcode):
        """
        Checks the database for a solution to the tripcode.
        """
        db_conn = sqlite3.connect(self.dbname)
        db_conn.text_factory = str

        db_cursor = db_conn.cursor()
        db_cursor.execute (
            '\n'.join ((
                    'SELECT solution',
                    'FROM   solutions',
                    'WHERE  tripcode=?'
             )),
            (tripcode,)
        )

        s = db_cursor.fetchone()
        db_cursor.close()
        db_conn.close()

        return None if s is None else s[0]
